# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "scott97"
    assignees:
      - "scott97"
    labels:
      - "chore"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    reviewers:
      - "scott97"
    assignees:
      - "scott97"
    labels:
      - "chore"
    schedule:
      interval: "monthly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    reviewers:
      - "scott97"
    assignees:
      - "scott97"
    labels:
      - "chore"
    schedule:
      interval: "monthly"
    groups:
      gomod:
        patterns:
          - "*"


  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "scott97"
    assignees:
      - "scott97"
    labels:
      - "chore"
      - "ci"
    schedule:
      interval: "monthly"
    groups:
      gh-actions:
        patterns:
          - "*"
