runtime: go121

env_variables:
  OPENFISH_CREDENTIALS: gs://ausocean/OpenFish-a197b0443246.json
  IAP: 'true'
  FILESTORE: 'false'
  JWT_AUDIENCE: '/projects/174291483773/apps/openfish'

main: ./cmd/openfish/main.go

handlers:

  - url: /api/.*
    script: auto
  
  # Serve index.html as /
  - url: /
    static_files: site/dist/index.html  
    upload: site/dist/index.html

  # TODO: Serve watch.html and streams.html from /watch and /streams urls.
  
  # Serve all files in dist.
  - url: /
    static_dir: site/dist
