runtime: go123

env_variables:
  OPENFISH_CREDENTIALS: gs://ausocean/OpenFish-a197b0443246.json
  OPENFISH_SECRETS: gs://ausocean/OpenFish-secrets.txt
  JWT: "true"
  IAP: "false"
  FILESTORE: "false"
  JWT_AUDIENCE: "openfish"
  JWT_ISSUER: "oceantv@appspot.gserviceaccount.com"

main: ./cmd/openfish/main.go

handlers:
  - url: /api/.*
    script: auto

  # Serve index.html as /
  - url: /
    static_files: site/dist/index.html
    upload: site/dist/index.html

  - url: /streams
    static_files: site/dist/streams.html
    upload: site/dist/streams.html

  - url: /watch
    static_files: site/dist/watch.html
    upload: site/dist/watch.html

  - url: /admin/capturesources
    static_files: site/dist/admin/capturesources.html
    upload: site/dist/admin/capturesources.html

  - url: /admin/users
    static_files: site/dist/admin/users.html
    upload: site/dist/admin/users.html

  - url: /admin/species
    static_files: site/dist/admin/species.html
    upload: site/dist/admin/species.html

  - url: /admin/videostreams
    static_files: site/dist/admin/videostreams.html
    upload: site/dist/admin/videostreams.html

  # Serve all files in dist.
  - url: /
    static_dir: site/dist
