POST http://localhost:3000/api/v1/capturesources HTTP/1.1
Content-Type: application/json

{
	"name": "Camera 1",
	"location": "-37.12345678,140.12345678",
	"camera_hardware": "rpi cam v2 - wide angle lens"
}

