name: Code checks

on: [push]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./cmd/openfish

    - name: Check formatting
      run: test -z $(gofmt -l .)

    - name: Test
      run: go test -v ./... -short

  webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: true
      
    - name: Build
      run: pnpm --filter ./openfish-webapp build
    
    - name: Check formatting
      run: pnpm --filter ./openfish-webapp ci:fmt

    - name: Lint
      run: pnpm --filter ./openfish-webapp ci:check

    - name: Test
      run: pnpm --filter ./openfish-webapp ci:test
